export interface TableData {
  header: string[];
  rows: string[][];
}

export const tableDataMap: { [key: string]: TableData } = {
  'Material Status': {
    header: [
      'Material Nr',
      'Material Name',
      'Required Qty',
      'Total Qty',
      'ERP Order Number',
      'Order Status',
      'Suppliers AB',
    ],
    rows: [
      ['1', 'test1', '3.4', '340.00', 'ERP-001', 'Available', 'Siemens'],
      ['2', 'test2', '5', '1240.00', 'ERP-002', 'Out of Stock', 'Apple'],
      ['3', 'test3', '10', '1000.00', 'ERP-003', 'Pending', 'Microsoft'],
      ['4', 'test4', '7', '700.00', 'ERP-004', 'Shipped', 'Amazon'],
      ['5', 'test5', '2', '200.00', 'ERP-005', 'Delivered', 'Tesla'],
      ['6', 'test6', '4', '400.00', 'ERP-006', 'Processing', 'Intel'],
    ],
  },
  'Commissioning Status': {
    header: [
      'Material Nr',
      'Material Name',
      'Total Required Quantity',
      'Commisioned Quantity',
      'Uncommisioned Quantity',
      'Percentage',
      'Details',
    ],
    rows: [
      ['1', 'test1', '3.4', '340.00', 'ERP-001', 'Available', 'Details'],
      ['2', 'test2', '5', '1240.00', 'ERP-002', 'Out of Stock', 'Details'],
      ['3', 'test3', '10', '1000.00', 'ERP-003', 'Pending', 'Details'],
      ['4', 'test4', '7', '700.00', 'ERP-004', 'Shipped', 'Details'],
      ['5', 'test5', '2', '200.00', 'ERP-005', 'Delivered', 'Details'],
      ['6', 'test6', '4', '400.00', 'ERP-006', 'Processing', 'Details'],
    ],
  },
  'Production Status': {
    header: [
      'Routing',
      'Workstep',
      'Rel.MatNr.',
      'Repeat',
      'Remaining Qty',
      'Total time',
      'Remaining Time',
      'Start Plan',
    ],
    rows: [
      [
        'Maschinelles Schneiden & Abisolieren (Automatic Cutting & Stripping)1',
        'test1',
        '3.4',
        '340.00',
        'ERP-001',
        'Available',
        'Siemens',
        '-',
      ],
      [
        'Maschinelles Schneiden & Abisolieren (Automatic Cutting & Stripping)2',
        'test2',
        '5',
        '1240.00',
        'ERP-002',
        'Out of Stock',
        'Apple',
        '-',
      ],
      [
        'Maschinelles Schneiden & Abisolieren (Automatic Cutting & Stripping)3',
        'test3',
        '10',
        '1000.00',
        'ERP-003',
        'Pending',
        'Microsoft',
        '-',
      ],
      [
        'Maschinelles Schneiden & Abisolieren (Automatic Cutting & Stripping)4',
        'test4',
        '7',
        '700.00',
        'ERP-004',
        'Shipped',
        'Amazon',
        '-',
      ],
      [
        'Maschinelles Schneiden & Abisolieren (Automatic Cutting & Stripping)5',
        'test5',
        '2',
        '200.00',
        'ERP-005',
        'Delivered',
        'Tesla',
        '-',
      ],
      [
        'Maschinelles Schneiden & Abisolieren (Automatic Cutting & Stripping)6',
        'test6',
        '4',
        '400.00',
        'ERP-006',
        'Processing',
        'Intel',
        '-',
      ],
    ],
  },
};
